# Generated by Django 5.1.1 on 2026-05-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipping_address_order_shipping_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
